### ISSUE TITLE
Win 7

### ISSUE THREAD

**Issue by harryray33** [Bernard-Borg/VideOVish#2]
Does this work with Win 7?

Thanks

**Comment by Bernard-Borg** [comment]
Unfortunately, since the technology being used (Tauri) doesn't support Windows 7, neither does this. The legacy version (Electron) is also not available on Windows 7, since both use WebView, which isn't available on Windows 7.

VideOVish is only available on Windows 10/11. Linux and MacOS versions are still under development.

**Comment by Bernard-Borg** [comment]
I'm testing out a change that should provide support for Windows 7 (64-bit), although there is no guarantee that everything will work smoothly.

**Comment by harryray33** [comment]
Great, thank you...

**Comment by Bernard-Borg** [comment]
Windows 7 support has been added in beta 2.0.1
